name: macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11]
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v2

    - name: Install qt6 using homebrew
      run: brew install qt6
        
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

    - name: Generate bundle for macOS
      working-directory: ${{github.workspace}}/scripts
      run: python3 bundle_macos.py 
  
    - name: Archive .app into tgz file
      working-directory: ${{github.workspace}}/build
      run: tar -czf Chollian\ Wallpaper.app.tgz Chollian\ Wallpaper.app
  
    - name: Upload a archived bundle
      uses: actions/upload-artifact@v2.2.4
      with:
        # Artifact name
        name: generated_bundle_${{matrix.build_type}}_${{matrix.os}}
        # A file, directory or wildcard pattern that describes what to upload
        path: ${{github.workspace}}/build/*.tgz
        
