name: Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
   
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.3
   
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '6.1.3'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        dir: '${{ github.workspace }}/ext/'
        install-deps: 'true'
        modules: 'qtbase'

    - name: Build CURL
      working-directory: ${{github.workspace}}/ext
      run: git clone https://github.com/curl/curl; 
           cd curl; 
           mkdir build; 
           cd build; 
           cmake ..; 
           MSBuild.exe CURL.sln -p:Configuration=Release

    - name: Build ChollianWallpaper
      working-directory: ${{github.workspace}}
      run: mkdir build; 
           cd build; 
           cmake -DCURL_LIBRARY=${{github.workspace}}/ext/curl/build/lib/Release/libcurl_imp.lib -DCURL_INCLUDE_DIR=${{github.workspace}}/ext/curl/include ..; 
           MSBuild.exe ChollianWallpaper.sln -p:Configuration=Release
    
    - name: Generate Bundle (experimental)
      working-directory: ${{github.workspace}}/build
      run: mkdir bundle; 
           cp Release/ChollianWallpaper.exe bundle/ChollianWallpaper.exe; 
           cp ${{github.workspace}}/ext/curl/build/lib/Release/libcurl.dll bundle/libcurl.dll;
           windeployqt.exe bundle/ChollianWallpaper.exe
           
    - name: Upload a archived bundle
      uses: actions/upload-artifact@v2.2.4
      with:
        # Artifact name
        name: generated_bundle
        # A file, directory or wildcard pattern that describes what to upload
        path: ${{github.workspace}}/build/bundle
    

