name: Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
   
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.3
   
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '6.1.3'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        dir: '${{ github.workspace }}/ext/'
        install-deps: 'true'
        modules: 'qtbase'

    - name: Download CURL
      working-directory: ${{github.workspace}}/ext
      run: cd ${{github.workspace}}/ext;
           curl.exe --output curl.zip https://curl.se/windows/dl-7.79.1/curl-7.79.1-win64-mingw.zip;
           tar -xvzf .\curl.zip;
           mv ./curl-7.79.1-win64-mingw ./curl;

    - name: Build ChollianWallpaper (Release configuration)
      working-directory: ${{github.workspace}}
      run: mkdir build_release; 
           cd build_release; 
           cmake -DCURL_LIBRARY=${{github.workspace}}/ext/curl/lib/libcurl.dll.a -DCURL_INCLUDE_DIR=${{github.workspace}}/ext/curl/include ..; 
           MSBuild.exe ChollianWallpaper.sln -p:Configuration=Release
    
    - name: Build ChollianWallpaper (Debug configuration)
      working-directory: ${{github.workspace}}
      run: mkdir build_debug; 
           cd build_debug; 
           cmake -DCURL_LIBRARY=${{github.workspace}}/ext/curl/lib/libcurl.dll.a -DCURL_INCLUDE_DIR=${{github.workspace}}/ext/curl/include ..; 
           MSBuild.exe ChollianWallpaper.sln -p:Configuration=Debug
    
    - name: Generate Bundle (Release) (experimental)
      working-directory: ${{github.workspace}}/build_release
      run: mkdir bundle_release; 
           cp Release/ChollianWallpaper.exe bundle_release/ChollianWallpaper.exe; 
           cp ${{github.workspace}}/resources bundle_release/resources -r; 
           cp ${{github.workspace}}/ext/curl/bin/libcurl-x64.dll bundle_release/libcurl-x64.dll;
           windeployqt.exe bundle_release/ChollianWallpaper.exe
           
    - name: Generate Bundle (Debug) (experimental)
      working-directory: ${{github.workspace}}/build_debug
      run: mkdir bundle_debug; 
           cp Debug/ChollianWallpaper.exe bundle_debug/ChollianWallpaper.exe; 
           cp ${{github.workspace}}/resources bundle_debug/resources -r; 
           cp ${{github.workspace}}/ext/curl/bin/libcurl-x64.dll bundle_debug/libcurl-x64.dll;
           windeployqt.exe bundle_debug/ChollianWallpaper.exe
           
    - name: Upload a archived bundle (Release)
      uses: actions/upload-artifact@v2.2.4
      with:
        # Artifact name
        name: generated_bundle_release
        # A file, directory or wildcard pattern that describes what to upload
        path: ${{github.workspace}}/build_release/bundle_release
    
    - name: Upload a archived bundle (Debug)
      uses: actions/upload-artifact@v2.2.4
      with:
        # Artifact name
        name: generated_bundle_debug
        # A file, directory or wildcard pattern that describes what to upload
        path: ${{github.workspace}}/build_debug/bundle_debug
