name: Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v2
   
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.3
   
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '6.1.3'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        dir: '${{ github.workspace }}/ext/'
        install-deps: 'true'
        modules: 'qtbase'

    - name: Download CURL
      working-directory: ${{github.workspace}}/ext
      run: cd ${{github.workspace}}/ext;
           curl.exe --output curl.zip https://curl.se/windows/dl-7.79.1/curl-7.79.1-win64-mingw.zip;
           tar -xvzf .\curl.zip;
           mv ./curl-7.79.1-win64-mingw ./curl;

    - name: Build ChollianWallpaper
      working-directory: ${{github.workspace}}
      run: mkdir build_${{matrix.build_type}}; 
           cd build_${{matrix.build_type}}; 
           cmake -DCURL_LIBRARY=${{github.workspace}}/ext/curl/lib/libcurl.dll.a -DCURL_INCLUDE_DIR=${{github.workspace}}/ext/curl/include ..; 
           MSBuild.exe ChollianWallpaper.sln -p:Configuration=${{matrix.build_type}}
    
    - name: Generate Bundle (experimental)
      working-directory: ${{github.workspace}}/build_${{matrix.build_type}}
      run: mkdir bundle_${{matrix.build_type}}; 
           cp ${{matrix.build_type}}/ChollianWallpaper.exe bundle_${{matrix.build_type}}/ChollianWallpaper.exe; 
           cp ${{github.workspace}}/resources bundle_${{matrix.build_type}}/resources -r; 
           cp ${{github.workspace}}/ext/curl/bin/libcurl-x64.dll bundle_${{matrix.build_type}}/libcurl-x64.dll;
           windeployqt.exe bundle_${{matrix.build_type}}/ChollianWallpaper.exe
           
    - name: Upload a archived bundle
      uses: actions/upload-artifact@v2.2.4
      with:
        # Artifact name
        name: generated_bundle_${{matrix.build_type}}
        # A file, directory or wildcard pattern that describes what to upload
        path: ${{github.workspace}}/build_${{matrix.build_type}}/bundle_${{matrix.build_type}}
